### PR TITLE
Viewer/Editor replacing TextLineNumbersPanel with RTextScrollPane, may fix #841

### LINKED ISSUE #841: NPE when opening text viewer
I've noticed the following NPE in the log when opening the text viewer:
```
2023-01-14 13:18:07.281 [Thread-3] TRACE c.m.commons.io.EncodingDetector:132 - bestMatch getName()=ISO-8859-2, getConfidence()=33
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.awt.Component.getFont()" because "c" is null
        at org.fife.ui.rsyntaxtextarea.SyntaxView.calculateLongestLine(SyntaxView.java:103)
        at org.fife.ui.rsyntaxtextarea.SyntaxView.updateMetrics(SyntaxView.java:904)
        at org.fife.ui.rsyntaxtextarea.SyntaxView.setSize(SyntaxView.java:812)
        at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1823)
        at java.desktop/javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:948)
        at java.desktop/javax.swing.plaf.basic.BasicTextAreaUI.getPreferredSize(BasicTextAreaUI.java:121)
        at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1734)
        at java.desktop/javax.swing.JTextArea.getPreferredSize(JTextArea.java:623)
        at com.mucommander.viewer.text.TextLineNumbersPanel.lambda$documentChanged$0(TextLineNumbersPanel.java:314)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### PR DESCRIPTION
**Pull request by pskowronek**
Viewer/Editor replacing TextLineNumbersPanel with RTextScrollPane:
- may fix #841
- additionally, the line number panel has Fold Indicator

obraz

### CODE REVIEW

File: mucommander-core/src/main/java/com/mucommander/ui/viewer/FileFrame.java [hunk 1]
```diff
@@ -1,147 +1,146 @@
...
-    // Abstract methods //
-    //////////////////////
-
-    protected abstract String getGenericErrorDialogTitle();
-
-    protected abstract String getGenericErrorDialogMessage();
-
-    protected abstract FilePresenter createFilePresenter(AbstractFile file) throws UserCancelledException;
-}
+package com.mucommander.ui.viewer;
```
Comment (pskowronek) [inline mucommander-core/src/main/java/com/mucommander/ui/viewer/FileFrame.java:1]: this probably happened after rebase (re-formatting of a whole file)

Comment (ahadas) [reply mucommander-core/src/main/java/com/mucommander/ui/viewer/FileFrame.java:1]: ack

**Review by ahadas — APPROVED** [review]
